repos:
  # --- Python: isort ---
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        exclude: |
          (?x)(
            third_party/ |
            fbs_schema/ |
            python/mininn/mininn_fbs/
          )

  # --- Python: black ---
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        exclude: |
          (?x)(
            third_party/ |
            fbs_schema/ |
            python/mininn/mininn_fbs/
          )

  # --- C/C++: clang-format ---
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.7
    hooks:
      - id: clang-format
        args: ["-style=google", "-i"]
        exclude: |
          (?x)(
            third_party/ |
            fbs_schema/ |
            mininn/parser/mininn_generated.h
          )