name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install Dependencies
      run: |
        pip install cmake
        pip install build

    - name: Build
      run: |
        python .\build_mininn.py --target windows --generator vs2022 --compiler cl --wheel

    - name: Zip Windows SDK
      run: |
        zip -r mininn-windows-sdk.zip .\build\install\*

    - name: Upload mininn artifact
      uses: actions/upload-artifact@v4
      with:
        name: mininn-windows
        path: |
          mininn-windows-sdk.zip
          python/dist/mininn-*.whl

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install Dependencies
      run: |
        pip install cmake
        pip install build
        pip install auditwheel
        pip install patchelf

    - name: Build
      run: |
        python ./build_mininn.py --target linux --generator ninja --compiler clang --wheel
        auditwheel repair python/dist/mininn-*.whl

    - name: Zip Linux SDK
      run: |
        zip -r mininn-linux-sdk.zip ./build/install/*

    - name: Upload mininn artifact
      uses: actions/upload-artifact@v4
      with:
        name: mininn-linux
        path: |
          mininn-linux-sdk.zip
          wheelhouse/mininn-*.whl


  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install Dependencies
      run: |
        pip install cmake
        pip install build

    - name: Build (universal2)
      run: |
        python ./build_mininn.py --target mac --generator ninja --compiler clang --wheel

    - name: Zip macOS SDK
      run: |
        zip -r mininn-macos-sdk.zip ./build/install/*

    - name: Upload mininn Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mininn-macos
        path: |
          mininn-macos-sdk.zip
          python/dist/mininn-*.whl

  release:
    needs: [windows, linux, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: mininn-windows
          path: release/windows/

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: mininn-linux
          path: release/linux/

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: mininn-macos
          path: release/macos/

      # you need to add Read and write permissions in Settings → Actions → General → Workflow permission
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/windows/mininn-windows-sdk.zip
            release/windows/python/dist/mininn-*.whl
            release/linux/mininn-linux-sdk.zip
            release/linux/wheelhouse/mininn-*.whl
            release/macos/mininn-macos-sdk.zip
            release/macos/python/dist/mininn-*.whl

  # need config by https://docs.pypi.org/trusted-publishers/adding-a-publisher/
  pypi-publish:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: pypi
      url: https://pypi.org/p/mininn

    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: mininn-windows
          path: release/windows/

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: mininn-linux
          path: release/linux/

      - name: Download Mac Artifact
        uses: actions/download-artifact@v4
        with:
          name: mininn-macos
          path: release/macos/

      - name: Move Windows whl to release folder
        run: |
          mkdir dist
          cd release/windows
          mv python/dist/mininn-*.whl ../../dist

      - name: Move Linux whl to release folder
        run: |
          cd release/linux
          mv wheelhouse/mininn-*.whl ../../dist

      - name: Move Mac whl to release folder
        run: |
          cd release/macos
          mv python/dist/mininn-*.whl ../../dist

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/